// <auto-generated />
namespace EditoraV3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Banco_Completo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Banco_Completo));
        
        string IMigrationMetadata.Id
        {
            get { return "202003111331500_Banco_Completo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
